FROM traefik:v2.1

LABEL container.name="traefik"
LABEL container.version="2.2"

# ADD traefik.yaml /etc/traefik/
# ADD traefik.toml /etc/traefik/

#CMD ["--providers.docker=true", "--providers.docker.exposedbydefault=false"]

