version: '3'

services:

  reverse-proxy:
     build:
       context: .
       dockerfile: Dockerfile
     restart: always
     networks:
       - proxy
     ports:
       - "80:80"
       - "443:443"
       # The Web UI (enabled by --api.insecure=true)
       - "2080:8080"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - $PWD/acme.json:/acme.json
       - $PWD/traefik.yaml:/etc/traefik/traefik.yaml
       - $PWD/dynamic:/etc/traefik/dynamic:ro

networks:
  proxy:
    external: true
