version: '3'

services:

  reverse-proxy:
     image: traefik:local
     command: --api.insecure=true --providers.docker
     ports:
       - "80:80"
       # The Web UI (enabled by --api.insecure=true)
       - "2080:8080"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
