---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

ping:
  entryPoint: "web"

providers:
  file:
    directory: "/etc/traefik/dynamic/"

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

log:
  filePath: "/var/log/traefik.log"
  format: json
  level: debug

accessLog:
  filePath: "/var/log/access.log"
  format: json

metrics:
  prometheus:
    addServicesLabels: true
    addEntryPointsLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

acme:
  email: "giannis.pin@gmail.com"
  storage: "acme.json"
  entryPoint: "websecure"
  onHostRule: true
  caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  httpChallenge:
    entrypoint: "web"

  domains:
    main: "ipinak.gr"
    sans: "*.ipinak.gr"

