http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      service: api@internal
      middlewares:
        - whitelist

    metrics:
      rule: "PathPrefix(`/metrics`)"
      service: prometheus@internal
      entryPoint: traefik
      middlewares:
        - whitelist

  middlewares:
    whitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.0.11"
          - "192.168.0.12"
          - "192.168.0.13"
          - "192.168.0.14"
          - "192.168.0.15"
          - "192.168.0.16"
          - "192.168.0.17"
          - "192.168.0.200"

