version: '2'

services:
    db_data:
        image: alpine:latest
        volumes:
            - ./database_data:/var/lib/mysql:rw
    mysql5.7:
        image: mysql:5.7
        container_name: my_database
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
            - MYSQL_ROOT_PASSWORD=root_pass
        volumes:
            - ./conf.d:/etc/mysql/conf.d
        volumes_from:
            - db_data

volumes:
    db_data:
        driver: "local"
